### ISSUE TITLE
Users want a search bar to search up room name

### ISSUE THREAD

**Issue by FindingDorri** [CS4360-Senior-Experience/UniTrail#42]
- [x] Search Bar
- [x] Query database by room name and number
- [x] Autofill suggestions based on user input

**Comment by esundbla** [comment]
Completed and pushed to back end in testing.dart  https://github.com/CS4360-Senior-Experience/UniTrail/pull/57
Linked Database,
Called for list elements using an async function
Populate the list tool and reserve the responses.
